# Generated by Django 5.0.1 on 2024-02-04 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('actions', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
